version: "3"

services:
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=Europe/Amsterdam
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_SCHEDULE=0 0 * * * *
  scanner:
    image: ghcr.io/stetsed-org/project-overwatch-scanner:main
    env_file:
      - .env
    volumes:
      - ./configuration.json:/app/configuration.json
